host: 127.0.0.1:8888/api
info:
  contact: {}
  license: {}
  title: go-echo-api Api文档
  version: "1.0"
paths:
  /eg:
    post:
      consumes:
      - application/json
      parameters:
      - default: ''''''
        description: 用戶名
        in: formData
        name: name
        required: true
        type: string
      - default: 22
        description: 年齡
        in: formData
        name: age
        required: true
        type: integer
      - default: ''''''
        description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      summary: eg
      tags:
      - eg
swagger: "2.0"
